import { Metadata } from 'next'
import ServiceDetail from '../ServiceDetail'
import { FiMail, FiSend, FiBarChart2, FiLayout, FiUsers, FiShield, FiZap, FiCpu, FiGlobe } from 'react-icons/fi'

export const metadata: Metadata = { title: 'Professional Email Support — Cognixeno Tech' }

export default function EmailSupportPage() {
  return (
    <ServiceDetail
      badge="Email Support"
      title="Professional Email Support"
      subtitle="Enterprise-grade email automation with smart routing, AI-powered responses, and analytics dashboards that supercharge your communication."
      accent="#F7B638"
      gradient="linear-gradient(180deg, rgba(247,182,56,0.06) 0%, #080810 100%)"
      features={[
        { title: 'Smart Email Routing', desc: 'AI automatically categorizes and routes emails to the right team or agent for fastest resolution.', icon: FiSend },
        { title: 'Template Engine', desc: 'Dynamic email templates with personalization, A/B testing, and automated follow-ups.', icon: FiLayout },
        { title: 'Analytics Dashboard', desc: 'Track open rates, response times, customer satisfaction, and team performance in real-time.', icon: FiBarChart2 },
        { title: 'AI Auto-Responses', desc: 'Intelligent responses generated by AI for common queries, reducing response time to seconds.', icon: FiMail },
        { title: 'Team Collaboration', desc: 'Shared inboxes, internal notes, assignments, and escalation workflows for team efficiency.', icon: FiUsers },
        { title: 'Spam & Security', desc: 'Advanced spam filtering, phishing detection, and email authentication (SPF, DKIM, DMARC).', icon: FiShield },
      ]}
      process={[
        { title: 'Email Audit', desc: 'Analyzing your current email workflows, volume, and pain points.' },
        { title: 'System Design', desc: 'Designing the email infrastructure with routing rules and automation triggers.' },
        { title: 'Template Creation', desc: 'Building responsive email templates and automated sequence flows.' },
        { title: 'AI Training', desc: 'Training AI models on your email history for smart auto-responses.' },
        { title: 'Launch & Optimize', desc: 'Going live with continuous A/B testing and performance optimization.' },
      ]}
      techStack={['SendGrid', 'Mailgun', 'AWS SES', 'SMTP', 'IMAP', 'Node.js', 'Redis', 'PostgreSQL', 'GPT-4', 'React Email']}
      relatedServices={[
        { name: 'AI Automation', href: '/services/ai-automation', accent: '#E1FF51', icon: FiZap },
        { name: 'AI-Powered Solutions', href: '/services/ai-solutions', accent: '#C8A8E9', icon: FiCpu },
        { name: 'Web Development', href: '/services/web-development', accent: '#FF947A', icon: FiGlobe },
      ]}
    />
  )
}
